automate the process of generate admission controller tls certs in VPA via initContainer

diff --git a/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml b/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
--- a/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
+++ b/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
@@ -18,6 +18,51 @@ spec:
       securityContext:
         runAsNonRoot: true
         runAsUser: 65534 # nobody
+      initContainers:
+        - name: cert-generator
+          image: alpine/openssl:latest
+          command: [ "/bin/sh", "-c" ]
+          volumeMounts:
+            - name: tls-certs
+              mountPath: "/tmp/vpa-certs"
+          args:
+            - |
+              set -o errexit
+              set -o nounset
+              set -o pipefail
+              
+              CN_BASE="vpa_webhook"
+              TMP_DIR="/tmp/vpa-certs"
+              
+              echo "Generating certs for the VPA Admission Controller in ${TMP_DIR}."
+              mkdir -p ${TMP_DIR}
+              cat > ${TMP_DIR}/server.conf << EOF
+              [req]
+              req_extensions = v3_req
+              distinguished_name = req_distinguished_name
+              [req_distinguished_name]
+              [ v3_req ]
+              basicConstraints = CA:FALSE
+              keyUsage = nonRepudiation, digitalSignature, keyEncipherment
+              extendedKeyUsage = clientAuth, serverAuth
+              subjectAltName = DNS:vpa-webhook.kube-system.svc
+              EOF
+              
+              # Create a certificate authority
+              openssl genrsa -out ${TMP_DIR}/caKey.pem 2048
+              set +o errexit
+              openssl req -x509 -new -nodes -key ${TMP_DIR}/caKey.pem -days 100000 -out ${TMP_DIR}/caCert.pem -subj "/CN=${CN_BASE}_ca" -addext "subjectAltName = DNS:${CN_BASE}_ca"
+              if [[ $? -ne 0 ]]; then
+                echo "ERROR: Failed to create CA certificate for self-signing. If the error is \"unknown option -addext\", update your openssl version or deploy VPA from the vpa-release-0.8 branch."
+                exit 1
+              fi
+              set -o errexit
+              
+              # Create a server certificate
+              openssl genrsa -out ${TMP_DIR}/serverKey.pem 2048
+              # Note the CN is the DNS name of the service of the webhook.
+              openssl req -new -key ${TMP_DIR}/serverKey.pem -out ${TMP_DIR}/server.csr -subj "/CN=vpa-webhook.kube-system.svc" -config ${TMP_DIR}/server.conf -addext "subjectAltName = DNS:vpa-webhook.kube-system.svc"
+              openssl x509 -req -in ${TMP_DIR}/server.csr -CA ${TMP_DIR}/caCert.pem -CAkey ${TMP_DIR}/caKey.pem -CAcreateserial -out ${TMP_DIR}/serverCert.pem -days 100000 -extensions SAN -extensions v3_req -extfile ${TMP_DIR}/server.conf
       containers:
         - name: admission-controller
           image: registry.k8s.io/autoscaling/vpa-admission-controller:0.14.0
@@ -44,8 +89,7 @@ spec:
               containerPort: 8944
       volumes:
         - name: tls-certs
-          secret:
-            secretName: vpa-tls-certs
+          emptyDir: {}
 ---
 apiVersion: v1
 kind: Service
