Add envtest support when its k8s version has not yet been released

diff --git a/cluster-autoscaler/Makefile b/cluster-autoscaler/Makefile
--- a/cluster-autoscaler/Makefile
+++ b/cluster-autoscaler/Makefile
@@ -177,8 +177,12 @@ ENVTEST_K8S_VERSION ?= $(shell go list -m -f "{{ .Version }}" k8s.io/api | awk -
 setup-envtest: envtest ## Download the binaries required for ENVTEST in the local bin directory.
 	@echo "Setting up envtest binaries for Kubernetes version $(ENVTEST_K8S_VERSION)..."
 	@$(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path || { \
-		echo "Error: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
-		exit 1; \
+		echo "Warning: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
+		echo "Attempting fallback to latest available envtest binaries version."; \
+		$(ENVTEST) use latest --bin-dir $(LOCALBIN) -p path || { \
+			echo "Error: Failed to set up envtest binaries."; \
+			exit 1; \
+		}; \
 	}
 
 .PHONY: envtest
